updates actions workflow (for macOS)

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -107,6 +107,10 @@ jobs:
         echo "PATH=/usr/local/opt/gnu-sed/libexec/gnubin:$PATH" >> $GITHUB_ENV
         ## OpenMP
         echo "OMP_NUM_THREADS=2" >> $GITHUB_ENV
+        ## MPI
+        echo "MPI environment:"
+        echo "mpif90 on path: $(which mpif90)"
+        echo
         ## avoids MPI issue with number of slots
         echo "OMPI_MCA_rmaps_base_oversubscribe=1" >> $GITHUB_ENV
         echo "OMPI_MCA_rmaps_base_inherit=1" >> $GITHUB_ENV
@@ -122,6 +126,8 @@ jobs:
     - name: configure
       run: |
         ./configure
+        # checks exit code
+        if [[ $? -ne 0 ]]; then cat config.log; exit 1; fi
         echo "modifying external_libs/scotch/src/Makefile.inc"
         cp -v external_libs/scotch/src/Make.inc/Makefile.inc.i686_mac_darwin8 external_libs/scotch/src/Makefile.inc
 
